apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dimmler-com-tls
spec:
  secretName: dimmler-com
  issueRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: dimmler.com
  dnsNames:
    - dimmler.com
    - www.dimmler.com
